<a href="https://colab.research.google.com/github/sufairahmed/Codeing_Practice/blob/master/ksvm_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [0]:
dataset = pd.read_csv('abilities.csv')
X = dataset.iloc[:, [0,2]].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[    1     3]
 [    2     3]
 [    3     3]
 [    4     3]
 [    5     3]
 [    6     3]
 [    7     3]
 [    8     3]
 [    9     3]
 [   10     3]
 [   11     3]
 [   12     3]
 [   13     3]
 [   14     3]
 [   15     3]
 [   16     3]
 [   17     3]
 [   18     3]
 [   19     3]
 [   20     3]
 [   21     3]
 [   22     3]
 [   23     3]
 [   24     3]
 [   25     3]
 [   26     3]
 [   27     3]
 [   28     3]
 [   29     3]
 [   30     3]
 [   31     3]
 [   32     3]
 [   33     3]
 [   34     3]
 [   35     3]
 [   36     3]
 [   37     3]
 [   38     3]
 [   39     3]
 [   40     3]
 [   41     3]
 [   42     3]
 [   43     3]
 [   44     3]
 [   45     3]
 [   46     3]
 [   47     3]
 [   48     3]
 [   49     3]
 [   50     3]
 [   51     3]
 [   52     3]
 [   53     3]
 [   54     3]
 [   55     3]
 [   56     3]
 [   57     3]
 [   58     3]
 [   59     3]
 [   60     3]
 [   61     3]
 [   62     3]
 [   63     3]
 [   64     3]
 [   65     3]
 [   66     3]
 [   67   

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state = 0)

In [6]:
print(y_test)

[1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1
 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1]


## Encoding the categorical data

In [0]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])], remainder  = 'passthrough')
# X = np.array(ct.fit_transform(X))

In [0]:
# print(X)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# training Kernel SVM model on the dataset

In [10]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0) # Redial Basis Function
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

predict the result

In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


cofusion matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[17  0]
 [ 0 57]]


1.0

#visualisation of traing set result